apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashtopolis
spec:
  selector:
    matchLabels:
      run: hashtopolis
  replicas: 1
  template:
    metadata:
      labels:
        run: hashtopolis
    spec:
      containers:
      - name: hashtopolis
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 8Gi
        image: kwillia/hashtopolis-agent 
