apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
